experiment_name: jtvae_moses
seed: 42

model:
  vocab: models/external/jtvae/data/moses/vocab.txt
  checkpoint: models/external/jtvae/fast_molvae/moses-h450z56/model.iter-400000
  hidden_size: 450
  latent_size: 56
  depthT: 20
  depthG: 3

data:
  path: data/zinc_250.csv

output:
  dir: results/jtvae
  predictor_checkpoint: results/jtvae/jtvae_property_predictor.pt
