experiment_name: jtvae_cma_es_logp
seed: 42

model:
  vocab: models/external/jtvae/data/moses/vocab.txt
  checkpoint: models/external/jtvae/fast_molvae/moses-h450z56/model.iter-400000
  hidden_size: 450
  latent_size: 56
  depthT: 20
  depthG: 3

optimizer:
  name: cma_es
  sigma0: 0.5
  n_iter: 50
  popsize: 10
  n_seeds: 100
  target_property: logP

data:
  path: data/zinc_250.csv

output:
  dir: results
  results_file: results/jtvae/jtvae_cma_es_results.json
